/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpsellRouteImport } from './routes/upsell'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RastreioCodigoRouteImport } from './routes/rastreio.$codigo'
import { Route as AdminUtmifySondaRouteImport } from './routes/admin/utmify-sonda'
import { Route as AdminRastreiosRouteImport } from './routes/admin/rastreios'
import { Route as AdminRastreamentoRetroativoRouteImport } from './routes/admin/rastreamento-retroativo'
import { Route as AdminEmailMassaRouteImport } from './routes/admin/email-massa'
import { Route as ApiPublicPedidoStatusRouteImport } from './routes/api/public/pedido-status'
import { Route as ApiPublicAsaasWebhookRouteImport } from './routes/api/public/asaas-webhook'

const UpsellRoute = UpsellRouteImport.update({
  id: '/upsell',
  path: '/upsell',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RastreioCodigoRoute = RastreioCodigoRouteImport.update({
  id: '/rastreio/$codigo',
  path: '/rastreio/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUtmifySondaRoute = AdminUtmifySondaRouteImport.update({
  id: '/admin/utmify-sonda',
  path: '/admin/utmify-sonda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRastreiosRoute = AdminRastreiosRouteImport.update({
  id: '/admin/rastreios',
  path: '/admin/rastreios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRastreamentoRetroativoRoute =
  AdminRastreamentoRetroativoRouteImport.update({
    id: '/admin/rastreamento-retroativo',
    path: '/admin/rastreamento-retroativo',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEmailMassaRoute = AdminEmailMassaRouteImport.update({
  id: '/admin/email-massa',
  path: '/admin/email-massa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPedidoStatusRoute = ApiPublicPedidoStatusRouteImport.update({
  id: '/api/public/pedido-status',
  path: '/api/public/pedido-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsaasWebhookRoute = ApiPublicAsaasWebhookRouteImport.update({
  id: '/api/public/asaas-webhook',
  path: '/api/public/asaas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guia': typeof GuiaRoute
  '/obrigado': typeof ObrigadoRoute
  '/upsell': typeof UpsellRoute
  '/admin/email-massa': typeof AdminEmailMassaRoute
  '/admin/rastreamento-retroativo': typeof AdminRastreamentoRetroativoRoute
  '/admin/rastreios': typeof AdminRastreiosRoute
  '/admin/utmify-sonda': typeof AdminUtmifySondaRoute
  '/rastreio/$codigo': typeof RastreioCodigoRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/pedido-status': typeof ApiPublicPedidoStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guia': typeof GuiaRoute
  '/obrigado': typeof ObrigadoRoute
  '/upsell': typeof UpsellRoute
  '/admin/email-massa': typeof AdminEmailMassaRoute
  '/admin/rastreamento-retroativo': typeof AdminRastreamentoRetroativoRoute
  '/admin/rastreios': typeof AdminRastreiosRoute
  '/admin/utmify-sonda': typeof AdminUtmifySondaRoute
  '/rastreio/$codigo': typeof RastreioCodigoRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/pedido-status': typeof ApiPublicPedidoStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guia': typeof GuiaRoute
  '/obrigado': typeof ObrigadoRoute
  '/upsell': typeof UpsellRoute
  '/admin/email-massa': typeof AdminEmailMassaRoute
  '/admin/rastreamento-retroativo': typeof AdminRastreamentoRetroativoRoute
  '/admin/rastreios': typeof AdminRastreiosRoute
  '/admin/utmify-sonda': typeof AdminUtmifySondaRoute
  '/rastreio/$codigo': typeof RastreioCodigoRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/pedido-status': typeof ApiPublicPedidoStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guia'
    | '/obrigado'
    | '/upsell'
    | '/admin/email-massa'
    | '/admin/rastreamento-retroativo'
    | '/admin/rastreios'
    | '/admin/utmify-sonda'
    | '/rastreio/$codigo'
    | '/api/public/asaas-webhook'
    | '/api/public/pedido-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guia'
    | '/obrigado'
    | '/upsell'
    | '/admin/email-massa'
    | '/admin/rastreamento-retroativo'
    | '/admin/rastreios'
    | '/admin/utmify-sonda'
    | '/rastreio/$codigo'
    | '/api/public/asaas-webhook'
    | '/api/public/pedido-status'
  id:
    | '__root__'
    | '/'
    | '/guia'
    | '/obrigado'
    | '/upsell'
    | '/admin/email-massa'
    | '/admin/rastreamento-retroativo'
    | '/admin/rastreios'
    | '/admin/utmify-sonda'
    | '/rastreio/$codigo'
    | '/api/public/asaas-webhook'
    | '/api/public/pedido-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuiaRoute: typeof GuiaRoute
  ObrigadoRoute: typeof ObrigadoRoute
  UpsellRoute: typeof UpsellRoute
  AdminEmailMassaRoute: typeof AdminEmailMassaRoute
  AdminRastreamentoRetroativoRoute: typeof AdminRastreamentoRetroativoRoute
  AdminRastreiosRoute: typeof AdminRastreiosRoute
  AdminUtmifySondaRoute: typeof AdminUtmifySondaRoute
  RastreioCodigoRoute: typeof RastreioCodigoRoute
  ApiPublicAsaasWebhookRoute: typeof ApiPublicAsaasWebhookRoute
  ApiPublicPedidoStatusRoute: typeof ApiPublicPedidoStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upsell': {
      id: '/upsell'
      path: '/upsell'
      fullPath: '/upsell'
      preLoaderRoute: typeof UpsellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastreio/$codigo': {
      id: '/rastreio/$codigo'
      path: '/rastreio/$codigo'
      fullPath: '/rastreio/$codigo'
      preLoaderRoute: typeof RastreioCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/utmify-sonda': {
      id: '/admin/utmify-sonda'
      path: '/admin/utmify-sonda'
      fullPath: '/admin/utmify-sonda'
      preLoaderRoute: typeof AdminUtmifySondaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rastreios': {
      id: '/admin/rastreios'
      path: '/admin/rastreios'
      fullPath: '/admin/rastreios'
      preLoaderRoute: typeof AdminRastreiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rastreamento-retroativo': {
      id: '/admin/rastreamento-retroativo'
      path: '/admin/rastreamento-retroativo'
      fullPath: '/admin/rastreamento-retroativo'
      preLoaderRoute: typeof AdminRastreamentoRetroativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/email-massa': {
      id: '/admin/email-massa'
      path: '/admin/email-massa'
      fullPath: '/admin/email-massa'
      preLoaderRoute: typeof AdminEmailMassaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pedido-status': {
      id: '/api/public/pedido-status'
      path: '/api/public/pedido-status'
      fullPath: '/api/public/pedido-status'
      preLoaderRoute: typeof ApiPublicPedidoStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas-webhook': {
      id: '/api/public/asaas-webhook'
      path: '/api/public/asaas-webhook'
      fullPath: '/api/public/asaas-webhook'
      preLoaderRoute: typeof ApiPublicAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuiaRoute: GuiaRoute,
  ObrigadoRoute: ObrigadoRoute,
  UpsellRoute: UpsellRoute,
  AdminEmailMassaRoute: AdminEmailMassaRoute,
  AdminRastreamentoRetroativoRoute: AdminRastreamentoRetroativoRoute,
  AdminRastreiosRoute: AdminRastreiosRoute,
  AdminUtmifySondaRoute: AdminUtmifySondaRoute,
  RastreioCodigoRoute: RastreioCodigoRoute,
  ApiPublicAsaasWebhookRoute: ApiPublicAsaasWebhookRoute,
  ApiPublicPedidoStatusRoute: ApiPublicPedidoStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
