/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RastreioCodigoRouteImport } from './routes/rastreio.$codigo'
import { Route as AdminUtmifySondaRouteImport } from './routes/admin/utmify-sonda'
import { Route as AdminRastreiosRouteImport } from './routes/admin/rastreios'
import { Route as AdminRastreamentoRetroativoRouteImport } from './routes/admin/rastreamento-retroativo'
import { Route as AdminEmailMassaRouteImport } from './routes/admin/email-massa'
import { Route as ApiPublicVenopagWebhookTestRouteImport } from './routes/api/public/venopag-webhook-test'
import { Route as ApiPublicVenopagWebhookRouteImport } from './routes/api/public/venopag-webhook'
import { Route as ApiPublicPedidoStatusRouteImport } from './routes/api/public/pedido-status'
import { Route as ApiPublicKorvexWebhookRouteImport } from './routes/api/public/korvex-webhook'

const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RastreioCodigoRoute = RastreioCodigoRouteImport.update({
  id: '/rastreio/$codigo',
  path: '/rastreio/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUtmifySondaRoute = AdminUtmifySondaRouteImport.update({
  id: '/admin/utmify-sonda',
  path: '/admin/utmify-sonda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRastreiosRoute = AdminRastreiosRouteImport.update({
  id: '/admin/rastreios',
  path: '/admin/rastreios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRastreamentoRetroativoRoute =
  AdminRastreamentoRetroativoRouteImport.update({
    id: '/admin/rastreamento-retroativo',
    path: '/admin/rastreamento-retroativo',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEmailMassaRoute = AdminEmailMassaRouteImport.update({
  id: '/admin/email-massa',
  path: '/admin/email-massa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVenopagWebhookTestRoute =
  ApiPublicVenopagWebhookTestRouteImport.update({
    id: '/api/public/venopag-webhook-test',
    path: '/api/public/venopag-webhook-test',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVenopagWebhookRoute = ApiPublicVenopagWebhookRouteImport.update({
  id: '/api/public/venopag-webhook',
  path: '/api/public/venopag-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPedidoStatusRoute = ApiPublicPedidoStatusRouteImport.update({
  id: '/api/public/pedido-status',
  path: '/api/public/pedido-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKorvexWebhookRoute = ApiPublicKorvexWebhookRouteImport.update({
  id: '/api/public/korvex-webhook',
  path: '/api/public/korvex-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/obrigado': typeof ObrigadoRoute
  '/admin/email-massa': typeof AdminEmailMassaRoute
  '/admin/rastreamento-retroativo': typeof AdminRastreamentoRetroativoRoute
  '/admin/rastreios': typeof AdminRastreiosRoute
  '/admin/utmify-sonda': typeof AdminUtmifySondaRoute
  '/rastreio/$codigo': typeof RastreioCodigoRoute
  '/api/public/korvex-webhook': typeof ApiPublicKorvexWebhookRoute
  '/api/public/pedido-status': typeof ApiPublicPedidoStatusRoute
  '/api/public/venopag-webhook': typeof ApiPublicVenopagWebhookRoute
  '/api/public/venopag-webhook-test': typeof ApiPublicVenopagWebhookTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/obrigado': typeof ObrigadoRoute
  '/admin/email-massa': typeof AdminEmailMassaRoute
  '/admin/rastreamento-retroativo': typeof AdminRastreamentoRetroativoRoute
  '/admin/rastreios': typeof AdminRastreiosRoute
  '/admin/utmify-sonda': typeof AdminUtmifySondaRoute
  '/rastreio/$codigo': typeof RastreioCodigoRoute
  '/api/public/korvex-webhook': typeof ApiPublicKorvexWebhookRoute
  '/api/public/pedido-status': typeof ApiPublicPedidoStatusRoute
  '/api/public/venopag-webhook': typeof ApiPublicVenopagWebhookRoute
  '/api/public/venopag-webhook-test': typeof ApiPublicVenopagWebhookTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/obrigado': typeof ObrigadoRoute
  '/admin/email-massa': typeof AdminEmailMassaRoute
  '/admin/rastreamento-retroativo': typeof AdminRastreamentoRetroativoRoute
  '/admin/rastreios': typeof AdminRastreiosRoute
  '/admin/utmify-sonda': typeof AdminUtmifySondaRoute
  '/rastreio/$codigo': typeof RastreioCodigoRoute
  '/api/public/korvex-webhook': typeof ApiPublicKorvexWebhookRoute
  '/api/public/pedido-status': typeof ApiPublicPedidoStatusRoute
  '/api/public/venopag-webhook': typeof ApiPublicVenopagWebhookRoute
  '/api/public/venopag-webhook-test': typeof ApiPublicVenopagWebhookTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/obrigado'
    | '/admin/email-massa'
    | '/admin/rastreamento-retroativo'
    | '/admin/rastreios'
    | '/admin/utmify-sonda'
    | '/rastreio/$codigo'
    | '/api/public/korvex-webhook'
    | '/api/public/pedido-status'
    | '/api/public/venopag-webhook'
    | '/api/public/venopag-webhook-test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/obrigado'
    | '/admin/email-massa'
    | '/admin/rastreamento-retroativo'
    | '/admin/rastreios'
    | '/admin/utmify-sonda'
    | '/rastreio/$codigo'
    | '/api/public/korvex-webhook'
    | '/api/public/pedido-status'
    | '/api/public/venopag-webhook'
    | '/api/public/venopag-webhook-test'
  id:
    | '__root__'
    | '/'
    | '/obrigado'
    | '/admin/email-massa'
    | '/admin/rastreamento-retroativo'
    | '/admin/rastreios'
    | '/admin/utmify-sonda'
    | '/rastreio/$codigo'
    | '/api/public/korvex-webhook'
    | '/api/public/pedido-status'
    | '/api/public/venopag-webhook'
    | '/api/public/venopag-webhook-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ObrigadoRoute: typeof ObrigadoRoute
  AdminEmailMassaRoute: typeof AdminEmailMassaRoute
  AdminRastreamentoRetroativoRoute: typeof AdminRastreamentoRetroativoRoute
  AdminRastreiosRoute: typeof AdminRastreiosRoute
  AdminUtmifySondaRoute: typeof AdminUtmifySondaRoute
  RastreioCodigoRoute: typeof RastreioCodigoRoute
  ApiPublicKorvexWebhookRoute: typeof ApiPublicKorvexWebhookRoute
  ApiPublicPedidoStatusRoute: typeof ApiPublicPedidoStatusRoute
  ApiPublicVenopagWebhookRoute: typeof ApiPublicVenopagWebhookRoute
  ApiPublicVenopagWebhookTestRoute: typeof ApiPublicVenopagWebhookTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastreio/$codigo': {
      id: '/rastreio/$codigo'
      path: '/rastreio/$codigo'
      fullPath: '/rastreio/$codigo'
      preLoaderRoute: typeof RastreioCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/utmify-sonda': {
      id: '/admin/utmify-sonda'
      path: '/admin/utmify-sonda'
      fullPath: '/admin/utmify-sonda'
      preLoaderRoute: typeof AdminUtmifySondaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rastreios': {
      id: '/admin/rastreios'
      path: '/admin/rastreios'
      fullPath: '/admin/rastreios'
      preLoaderRoute: typeof AdminRastreiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rastreamento-retroativo': {
      id: '/admin/rastreamento-retroativo'
      path: '/admin/rastreamento-retroativo'
      fullPath: '/admin/rastreamento-retroativo'
      preLoaderRoute: typeof AdminRastreamentoRetroativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/email-massa': {
      id: '/admin/email-massa'
      path: '/admin/email-massa'
      fullPath: '/admin/email-massa'
      preLoaderRoute: typeof AdminEmailMassaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/venopag-webhook-test': {
      id: '/api/public/venopag-webhook-test'
      path: '/api/public/venopag-webhook-test'
      fullPath: '/api/public/venopag-webhook-test'
      preLoaderRoute: typeof ApiPublicVenopagWebhookTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/venopag-webhook': {
      id: '/api/public/venopag-webhook'
      path: '/api/public/venopag-webhook'
      fullPath: '/api/public/venopag-webhook'
      preLoaderRoute: typeof ApiPublicVenopagWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pedido-status': {
      id: '/api/public/pedido-status'
      path: '/api/public/pedido-status'
      fullPath: '/api/public/pedido-status'
      preLoaderRoute: typeof ApiPublicPedidoStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/korvex-webhook': {
      id: '/api/public/korvex-webhook'
      path: '/api/public/korvex-webhook'
      fullPath: '/api/public/korvex-webhook'
      preLoaderRoute: typeof ApiPublicKorvexWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ObrigadoRoute: ObrigadoRoute,
  AdminEmailMassaRoute: AdminEmailMassaRoute,
  AdminRastreamentoRetroativoRoute: AdminRastreamentoRetroativoRoute,
  AdminRastreiosRoute: AdminRastreiosRoute,
  AdminUtmifySondaRoute: AdminUtmifySondaRoute,
  RastreioCodigoRoute: RastreioCodigoRoute,
  ApiPublicKorvexWebhookRoute: ApiPublicKorvexWebhookRoute,
  ApiPublicPedidoStatusRoute: ApiPublicPedidoStatusRoute,
  ApiPublicVenopagWebhookRoute: ApiPublicVenopagWebhookRoute,
  ApiPublicVenopagWebhookTestRoute: ApiPublicVenopagWebhookTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
